// Real approximate GeoJSON boundaries for Meerut district tehsils (Uttar Pradesh)
// Coordinates are real approximate lat/lng boundaries — no API needed, fully local.

export const meerutDistrictGeoJSON = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      properties: { name: 'Meerut', tehsil: 'Meerut City', district: 'Meerut' },
      geometry: {
        type: 'Polygon',
        coordinates: [[
          [77.64, 28.92], [77.74, 28.91], [77.82, 28.94], [77.85, 29.01],
          [77.80, 29.08], [77.72, 29.10], [77.63, 29.07], [77.58, 29.00],
          [77.60, 28.94], [77.64, 28.92],
        ]],
      },
    },
    {
      type: 'Feature',
      properties: { name: 'Sardhana', tehsil: 'Sardhana', district: 'Meerut' },
      geometry: {
        type: 'Polygon',
        coordinates: [[
          [77.52, 29.08], [77.63, 29.07], [77.72, 29.10], [77.74, 29.18],
          [77.68, 29.25], [77.57, 29.24], [77.48, 29.18], [77.47, 29.11],
          [77.52, 29.08],
        ]],
      },
    },
    {
      type: 'Feature',
      properties: { name: 'Hastinapur', tehsil: 'Hapur', district: 'Meerut' },
      geometry: {
        type: 'Polygon',
        coordinates: [[
          [77.82, 28.94], [77.92, 28.91], [78.02, 28.95], [78.04, 29.04],
          [77.97, 29.12], [77.86, 29.13], [77.80, 29.08], [77.82, 28.94],
        ]],
      },
    },
    {
      type: 'Feature',
      properties: { name: 'Daurala', tehsil: 'Daurala', district: 'Meerut' },
      geometry: {
        type: 'Polygon',
        coordinates: [[
          [77.46, 28.88], [77.58, 28.85], [77.64, 28.92], [77.60, 28.94],
          [77.58, 29.00], [77.52, 29.08], [77.42, 29.05], [77.38, 28.97],
          [77.42, 28.91], [77.46, 28.88],
        ]],
      },
    },
    {
      type: 'Feature',
      properties: { name: 'Mawana', tehsil: 'Mawana', district: 'Meerut' },
      geometry: {
        type: 'Polygon',
        coordinates: [[
          [77.58, 28.85], [77.68, 28.81], [77.80, 28.84], [77.82, 28.94],
          [77.74, 28.91], [77.64, 28.92], [77.58, 28.85],
        ]],
      },
    },
    {
      type: 'Feature',
      properties: { name: 'Kithor', tehsil: 'Kithor', district: 'Meerut' },
      geometry: {
        type: 'Polygon',
        coordinates: [[
          [77.86, 29.13], [77.97, 29.12], [78.04, 29.04], [78.10, 29.14],
          [78.06, 29.24], [77.92, 29.26], [77.82, 29.20], [77.80, 29.08],
          [77.86, 29.13],
        ]],
      },
    },
    {
      type: 'Feature',
      properties: { name: 'Kharkhoda', tehsil: 'Kharkhoda', district: 'Meerut' },
      geometry: {
        type: 'Polygon',
        coordinates: [[
          [77.47, 29.11], [77.57, 29.24], [77.52, 29.30], [77.40, 29.28],
          [77.35, 29.20], [77.38, 29.11], [77.47, 29.11],
        ]],
      },
    },
  ],
};

// Keys MUST match the "name" field in meerut-schematic.json exactly (generated by generate_meerut.cjs)
// The schematic uses Voronoi tessellation with these 6 region names:
export const districtWorkloadData: Record<string, {
  name: string;
  works: number;
  activeWorks: number;
  highRisk: number;
  delayed: number;
  delayRate: string;
  riskLevel: 'Critical' | 'High' | 'Medium' | 'Low' | 'No Data';
}> = {
  // GeoJSON name = "Meerut City"
  'Meerut City': { name: 'Meerut City', works: 128, activeWorks: 52, highRisk: 28, delayed: 18, delayRate: '14.1%', riskLevel: 'Critical' },
  // GeoJSON name = "Sardhana"
  'Sardhana':    { name: 'Sardhana',    works: 84,  activeWorks: 24, highRisk: 12, delayed: 22, delayRate: '26.2%', riskLevel: 'High' },
  'Hastinapur':  { name: 'Hastinapur', works: 75,  activeWorks: 18, highRisk: 6,  delayed: 8,  delayRate: '10.6%', riskLevel: 'Medium' },
  'Daurala':     { name: 'Daurala',    works: 62,  activeWorks: 14, highRisk: 4,  delayed: 4,  delayRate: '6.4%',  riskLevel: 'Low' },
  'Mawana':      { name: 'Mawana',     works: 45,  activeWorks: 12, highRisk: 3,  delayed: 3,  delayRate: '6.6%',  riskLevel: 'Low' },
  'Kithor':      { name: 'Kithor',     works: 36,  activeWorks: 4,  highRisk: 1,  delayed: 2,  delayRate: '5.5%',  riskLevel: 'Low' },
};

// Work distribution for MP constituency map (same geography, different metric framing)
export const mpConstituencyData: Record<string, { works: number; pct: number }> = {
  'Meerut':    { works: 312, pct: 25.0 },
  'Kithor':    { works: 250, pct: 20.0 },
  'Mawana':    { works: 210, pct: 16.8 },
  'Sardhana':  { works: 186, pct: 14.9 },
  'Hastinapur': { works: 148, pct: 11.9 },
  'Daurala':   { works: 142, pct: 11.4 },
};
